<?php
    /**
     * ----------------
     *   提醒! 請注意!
     * ----------------
     * 若不確定已存在的語系變數用途是一樣的，
     * 則自行命名一組語系變數，
     * 以免後續變更造成不一致。
     */

    // 主版面
    $LANG_USER_REPASSWORD_ERROR2= "兩次密碼輸入的不一致";
    $LANG_PAGE_META             = "999康養財富計劃";
    $LANG_PAGE_COPYRIGHT        = "2017 aleen39.tw 版權所有."; // "2017 aleen39.tw All rights reserved.";
    $LANG_PAGE_VERSION          = "1.2 國際版";

    // Session(COOKIE) & Login
    $LANG_SESSION_AUTH_SUCCESS  = "登入成功！";
    $LANG_SESSION_AUTH_FAILURE  = "帳號或密碼輸入錯誤，請重新登入！";
    $LANG_SESSION_AUTH_LOCK     = "您的帳號已被鎖定，請於30分鐘後在重新登入！";
    $LANG_SESSION_AUTH_RETRY    = "帳號或密碼輸入錯誤，請重新登入！可嘗試登入次數：";
    $LANG_SESSION_AUTH_RETRY_LOCK = "登入錯誤次數超過3次，已被鎖定此帳號，請於30分鐘後在重新登入！";
    $LANG_SESSION_AUTH_VALIDATE_FAILURE = "驗證錯誤！";

    $LANG_USER_WELCOME          = "歡迎您來到999康養財富計劃";
    $LANG_USER_LOGIN            = "使用者登入";
    $LANG_USER_ACCOUNT          = "帳號";
    $LANG_USER_PASSWORD         = "密碼";
    $LANG_USER_SIGNIN           = "登入";
    $LANG_USER_SIGNIN_KEEP      = "記住密碼";
    $LANG_USER_REPASSWORD       = "確認密碼";
    $LANG_USER_NEED_REPASSWORD  = "請重覆輸入密碼";
    $LANG_USER_FORGET_PASS      = "忘記密碼";
    $LANG_USER_REPASSWORD_ERROR = "兩次密碼輸入的不一致";
?>
