<?php
    /**
     * ----------------
     *   提醒! 請注意!
     * ----------------
     * 1. 確認用途
     *     若不確定已存在的語系變數用途是一樣的，
     *     則自行命名一組語系變數，
     *     以免後續變更造成不一致。
     *
     * 2. 確認變數不重覆
     * ----------------
     */

    // 主版面
    $LANG_PAGE_META             = "999康養財富計劃";
    $LANG_PAGE_COPYRIGHT        = "2017 aleen39.tw 版權所有."; // "2017 aleen39.tw All rights reserved.";
    $LANG_PAGE_VERSION          = "1.2 國際版";

    // Session(COOKIE) & Login
    $LANG_SESSION_AUTH_SUCCESS  = "登入成功！";
    $LANG_SESSION_AUTH_FAILURE  = "帳號或密碼輸入錯誤，請重新登入！";
    $LANG_SESSION_AUTH_LOCK     = "您的帳號已被鎖定，請於30分鐘後在重新登入！";
    $LANG_SESSION_AUTH_RETRY    = "帳號或密碼輸入錯誤，請重新登入！可嘗試登入次數：";
    $LANG_SESSION_AUTH_RETRY_LOCK = "登入錯誤次數超過3次，已被鎖定此帳號，請於30分鐘後在重新登入！";
    $LANG_SESSION_AUTH_VALIDATE_FAILURE = "驗證錯誤！";

    // 使用者相關
    $LANG_USER_WELCOME          = "歡迎您來到999康養財富計劃";
    $LANG_USER_LOGIN            = "使用者登入";
    $LANG_USER_ACCOUNT          = "帳號";
    $LANG_USER_PASSWORD         = "密碼";
    $LANG_USER_SIGNIN           = "登入";
    $LANG_USER_SIGNIN_KEEP      = "記住密碼";
    $LANG_USER_REPASSWORD       = "確認密碼";
    $LANG_USER_NEED_REPASSWORD  = "請重覆輸入密碼";
    $LANG_USER_FORGET_PASS      = "忘記密碼";
    $LANG_USER_REPASSWORD_ERROR = "兩次密碼輸入的不一致";
    $LANG_USER_AUTH_SUCCESS     = "已認證";
    $LANG_USER_AUTH_FAILURE     = "未認證";
    $LANG_USER_GRADE            = "會員等級";
    $LANG_USER_NUMBER           = "會員編號";
    $LANG_USER_SINGUP_TIME      = "註冊時間";
    $LANG_USER_BONUS_CAPITAL    = "獎金帳戶";
    $LANG_USER_BONUS_BALANCE    = "財富金";
    $LANG_USER_BONUS_FUND       = "康養積分";

    // 系統
    $LANG_SYSTEM_BONUS_STORED   = "儲值";
    $LANG_SYSTEM_BONUS_TRANSFER = "互轉";
    $LANG_SYSTEM_READ_MORE      = "查看更多";
    $LANG_SYSTEM_NEWS           = "公告";
    $LANG_SYSTEM_NEWS_TIME      = "發佈時間";
    $LANG_SYSTEM_NEWS_CONTENT   = "公告內容";
    $LANG_SYSTEM_COMMON_FUNC    = "常用功能";
    $LANG_SYSTEM_COMMON_FUNC_1  = "註冊會員";
    $LANG_SYSTEM_COMMON_FUNC_2  = "帳戶明細";
    $LANG_SYSTEM_COMMON_FUNC_3  = "接點查詢";
    $LANG_SYSTEM_COMMON_FUNC_4  = "提現申請";
    $LANG_SYSTEM_COMMON_FUNC_5  = "聯繫客服";
    $LANG_SYSTEM_COMMON_FUNC_5  = "聯繫客服";
    $LANG_SYSTEM_USER_PV        = "我的PV收益";
    $LANG_SYSTEM_USER_PV_ADDITION = "新增獎金";
    $LANG_SYSTEM_USER_PV_HISTORY  = "歷史獎金";
    $LANG_SYSTEM_USER_BUSINESS  = "我的業務資訊";
    $LANG_SYSTEM_USER_BUSINESS_LEVEL   = "目前層數";
    $LANG_SYSTEM_USER_BUSINESS_PROMOTE = "推薦人數";
    $LANG_SYSTEM_CURRENCY       = "幣別";
    $LANG_SYSTEM_CURRENCY_USD   = "美元";
    $LANG_SYSTEM_CURRENCY_NT    = "新台幣";
    $LANG_SYSTEM_CURRENCY_RMB   = "人民幣";
    $LANG_SYSTEM_DELETE_CONFIRM = "你是否確定要刪除 %s 這筆資料？";
    $LANG_SYSTEM_ADD_DONE       = "新增完畢";
    $LANG_SYSTEM_EDIT_DONE      = "修改完畢";
    $LANG_SYSTEM_DEL_DONE       = "刪除完畢";

    // Oldman

?>
